name: Professor Jekyll Edits His config.yml
pygments: true

url:  http://silshack.github.io/professorjekyll/

authors:
  einstein:
      name: Albert Einstein
      prof: true
      gravatar: 
      website: http://www.relativity.com
      github: 
      twitter:
      about:  E=mc^2
  wittgenstein:
      name: Ludwig Wittgenstein
      prof: true
      gravatar:
      website: http://www.tractatus.com
      github:
      twitter:
      about:  E=mc^2
