name: SILShack Spring 2014
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

baseurl: /spring2014

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Spring 2014

authors:
  elliott:
      name: Elliott Hauser
      prof: true
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.elliotthauser.com
      github: eah13
      twitter: hauspoor
      about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Coursefork.org.  
  grant:
      name: Grant McLendon
      prof: true
      gravatar: eeb73c80c4450528bf5eac5f1dedae9e
      website: http://grantmclendon.com
      github: gerbal
      twitter: gerbal100
      about: Grant is a first year MSIS student. He's from Chapel Hil and like playing with new technologies and getting way in over his head.
  allen:
      name: Allen Lyons
      prof: false
      gravatar:
      website: http://www.unc.edu/~lyonsa/
      github: lyonsa
      twitter: lions8lyons
      about: Allen is a fourth year UNC undergraduate in the BSIS program. No idea what he is going to do after he graduates but hopefully he"'"ll be doing something that makes money. Likes playing with new tech, watch tv and movies, reading comic books, playing video games, and spending time with his friends and family. Depending on the whole job thing he may also be consuming a considerable amount of alcohol this semester.
