name: SILShack Spring 2014
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

baseurl: /spring2014

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Spring 2014

authors:
  zach:
      name: Zachary Williams
      prof: false
      gravatar: 0d0d432948d262195358f339768f1240
      website: http://www.unc.edu/~zlwillia
      github: zbay
      twitter: 
      about:  Zach is a sophomore Information Science major at UNC.
